name: ${project.name}
author: alyphen
version: ${project.version}
description: ${project.description}
main: com.seventh_root.atherna.waywardcharactersconnector.AthernaWaywardCharactersConnector
depend: [atherna, WaywardLib]
